### ISSUE TITLE
Submit Cool Python Snippets

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/snippets#1]
Submit python snippets that are useful.

**Comment by ikamalrawal** [comment]
Please assign this issue to me. I will try my best to improve it.

Regards
Kamal

**Comment by curiouspratik** [comment]
@AdityaJ7 Can I also  do this issue? This is my first time and I think I can help in this one.
Thanks!

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Can I also do this issue? This is my first time and I think I can help in this one.
> Thanks!

Sure @Pratik-Patil-p0212-m3108

**Comment by Kamesh-Mishra** [comment]
I would like to contribute OrderedDict Code Snippet, can you please assign me !!
