### ISSUE TITLE
Python snippet to check current date and time

### ISSUE THREAD

**Issue by vanigupta20024** [Python-World/snippets#16]
# Description
Python snippet to check current date and time using Datetime module

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by vanigupta20024** [comment]
Please assign this issue!

**Comment by AdityaJ7** [comment]
@vanigupta20024  the bot did that already

**Comment by vanigupta20024** [comment]
Yep!
