### ISSUE TITLE
Add requests snippet

### ISSUE THREAD

**Issue by jnoc** [Python-World/snippets#22]
# Description

Add a snippet to show how the requests module works

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by shubheshdwivedi** [comment]
Hi, can I work on this?

**Comment by jnoc** [comment]
just done this @shubheshdwivedi
